import type { PortfolioData } from '@/types'

export const portfolioData: PortfolioData = {
  name: 'Salah Uddin Selim',
  title: 'CSE Student & Software Engineer',
  tagline: 'Building intelligent systems with full-stack engineering, IoT, and AI.',
  bio: 'CSE student at United International University (GPA 3.68/4.0) with hands-on experience in full-stack web development, IoT systems, and algorithm design. Built 5 production-quality projects across Java, Python, PHP, C/C++, and Arduino. Award-winning project (6th Runner-Up, UIU Spring 2025). Seeking software engineering or research roles to build scalable, impactful solutions.',
  avatar: '',
  location: 'Dhaka, Bangladesh',
  email: 'sselim223512@bscse.uiu.ac.bd',
  resumeUrl: '',
  available: true,
  navItems: [
    { label: 'Projects', href: '/projects' },
    { label: 'Credentials', href: '/credentials' },
    { label: 'Forge', href: '/forge' },
    { label: 'Persona', href: '/persona' },
  ],
  socialLinks: [
    { name: 'GitHub', url: 'https://github.com/salahuddinselim', icon: 'github' },
    { name: 'Email', url: 'mailto:sselim223512@bscse.uiu.ac.bd', icon: 'email' },
  ],
  skills: [
    { name: 'Python', category: 'Languages', proficiency: 85 },
    { name: 'Java', category: 'Languages', proficiency: 80 },
    { name: 'C', category: 'Languages', proficiency: 75 },
    { name: 'C++', category: 'Languages', proficiency: 70 },
    { name: 'PHP', category: 'Languages', proficiency: 75 },
    { name: 'JavaScript', category: 'Languages', proficiency: 78 },
    { name: 'HTML/CSS', category: 'Languages', proficiency: 82 },
    { name: 'JavaFX', category: 'Frameworks', proficiency: 80 },
    { name: 'Bootstrap', category: 'Frameworks', proficiency: 78 },
    { name: 'MySQL', category: 'Databases', proficiency: 80 },
    { name: 'Arduino', category: 'Hardware & IoT', proficiency: 75 },
    { name: 'Git', category: 'Tools', proficiency: 80 },
    { name: 'Socket Programming', category: 'Concepts', proficiency: 75 },
    { name: 'DSA', category: 'Concepts', proficiency: 80 },
    { name: 'OOP', category: 'Concepts', proficiency: 85 },
  ],
  projects: [
    {
      title: 'Multilevel Puzzle Solving Game',
      slug: 'puzzle-solving-game',
      description: 'Team-based desktop app with 5 logic games and shared progression.',
      longDescription: 'Architected a team-based desktop app with 5 logic games (Tower of Hanoi, Jigsaw, Crossword, Number Guess, Color Mapping) and shared progression synced across 3-member teams via MySQL. Implemented real-time group chat with Java Socket Programming and multithreading. Engineered collaborative level-unlocking: any team member\'s completion instantly unlocks that level for the whole team. Won 6th Runner-Up at UIU Spring 2025.',
      technologies: ['Java', 'JavaFX', 'MySQL', 'Socket Programming'],
      category: 'Desktop',
      image: '/placeholder.svg',
      githubUrl: 'https://github.com/salahuddinselim/PuzzleSolving-Game',
      featured: true,
      year: 2025,
    },
    {
      title: 'Tournament Management System — TournyMate',
      slug: 'tourny-mate',
      description: 'Full-stack web platform for end-to-end tournament administration.',
      longDescription: 'Built a full-stack web platform for end-to-end tournament administration — registration, automated bracket scheduling, live score updates, and role-based admin controls. Developed secure PHP/MySQL backend with player profiles, performance tracking, and admin moderation (delete players/tournaments, read messages).',
      technologies: ['PHP', 'MySQL', 'Bootstrap', 'JavaScript'],
      category: 'Full Stack',
      image: '/placeholder.svg',
      githubUrl: 'https://github.com/salahuddinselim/tourny_mate',
      featured: true,
      year: 2024,
    },
    {
      title: 'Automated Fish Pond Monitoring System',
      slug: 'fish-pond-monitor',
      description: 'Smart IoT system with 5 sensors for automated fish pond management.',
      longDescription: 'Deployed smart IoT system with 5 sensors (temperature, pH, turbidity, gas, ultrasonic) on Arduino. Automated corrective actions — water exchange, pH balancing, food dispensing — via servo motors and L298N drivers. Eliminated manual intervention through closed-loop C++ control logic that reads thresholds and fires actuators in real time.',
      technologies: ['Arduino', 'C++', 'IoT'],
      category: 'IoT',
      image: '/placeholder.svg',
      githubUrl: 'https://github.com/salahuddinselim/Automated-Fish-Pond',
      featured: true,
      year: 2024,
    },
    {
      title: 'AI Voice Assistant',
      slug: 'ai-voice-assistant',
      description: 'Python voice assistant with NL speech parsing and TTS output.',
      longDescription: 'Built a Python voice assistant with NL speech parsing, TTS output, real-time web search (Google Custom Search API), OS automation, reminder scheduling, and joke generation (PyJokes).',
      technologies: ['Python', 'SpeechRecognition', 'Pyttsx3', 'Google API'],
      category: 'AI',
      image: '/placeholder.svg',
      githubUrl: 'https://github.com/salahuddinselim/Voice-Assistance',
      featured: false,
      year: 2024,
    },
    {
      title: 'Player Information System — Bangladesh Cricket',
      slug: 'player-info-system',
      description: 'Menu-driven CLI to manage Bangladesh cricket player stats.',
      longDescription: 'Developed a menu-driven CLI in C to manage player stats (batting avg, experience, match records) with O(n) search, sort, and statistical queries (top scorer, most experienced) using structures and file handling.',
      technologies: ['C', 'File I/O'],
      category: 'CLI',
      image: '/placeholder.svg',
      githubUrl: 'https://github.com/salahuddinselim/Player-Information-System',
      featured: false,
      year: 2023,
    },
  ],
  experience: [
    {
      company: 'United International University',
      role: 'B.Sc. in Computer Science & Engineering',
      period: '2022 — Present',
      description: 'GPA: 3.68 / 4.00 (112 / 137 credits completed). Active in software project competitions.',
    },
    {
      company: 'Pirganj Govt. College',
      role: 'Higher Secondary Certificate (HSC)',
      period: '2018 — 2020',
      description: 'GPA: 5.00 / 5.00. Science group.',
    },
    {
      company: 'Pirganj Pilot High School',
      role: 'Secondary School Certificate (SSC)',
      period: '2013 — 2018',
      description: 'GPA: 5.00 / 5.00.',
    },
  ],
  testimonials: [],
}
