import type { IconType } from "react-icons"
import { FaJava, FaHtml5, FaCss3Alt, FaBootstrap, FaGitAlt, FaGithub } from "react-icons/fa"
import {
  SiC,
  SiCplusplus,
  SiExpress,
  SiJavascript,
  SiMysql,
  SiNodedotjs,
  SiOpenjdk,
  SiPython,
  SiStreamlit,
  SiPhp,
  SiArduino,
  SiIntellijidea,
  SiCodeforces,
} from "react-icons/si"

export type TechTier = "Core" | "Working" | "Learning"

export interface TechStackItem {
  name: string
  category: "languages" | "frontend" | "backend" | "iot" | "tools"
  brandColor: string
  textColor?: string
  icon: IconType
  tier: TechTier
  lastUsed: string
  projects: Array<{ label: string; href: string }>
}

export const TECH_STACK: TechStackItem[] = [
  {
    name: "C",
    category: "languages",
    brandColor: "#A8B9CC",
    icon: SiC,
    tier: "Core",
    lastUsed: "May 2026",
    projects: [{ label: "DSA Problem Sets", href: "/projects" }],
  },
  {
    name: "C++",
    category: "languages",
    brandColor: "#00599C",
    icon: SiCplusplus,
    tier: "Core",
    lastUsed: "May 2026",
    projects: [{ label: "Algorithm Visualizer", href: "/projects" }],
  },
  {
    name: "Java",
    category: "languages",
    brandColor: "#F89820",
    icon: FaJava,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Desktop Management Tool", href: "/projects" }],
  },
  {
    name: "JavaScript",
    category: "languages",
    brandColor: "#F7DF1E",
    textColor: "#F8FAFC",
    icon: SiJavascript,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Portfolio Frontend", href: "/projects" }],
  },
  {
    name: "PHP",
    category: "languages",
    brandColor: "#777BB4",
    icon: SiPhp,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "TournyMate", href: "/projects" }],
  },
  {
    name: "Node.js",
    category: "backend",
    brandColor: "#339933",
    icon: SiNodedotjs,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "API Integrations", href: "/projects" }],
  },
  {
    name: "Express",
    category: "backend",
    brandColor: "#D1D5DB",
    icon: SiExpress,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "REST Backend", href: "/projects" }],
  },
  {
    name: "Python",
    category: "languages",
    brandColor: "#3776AB",
    icon: SiPython,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Automation Scripts", href: "/projects" }],
  },
  {
    name: "Streamlit",
    category: "frontend",
    brandColor: "#FF4B4B",
    icon: SiStreamlit,
    tier: "Working",
    lastUsed: "April 2026",
    projects: [{ label: "Analytics Dashboard", href: "/projects" }],
  },
  {
    name: "HTML5",
    category: "frontend",
    brandColor: "#E34F26",
    icon: FaHtml5,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Portfolio Frontend", href: "/projects" }],
  },
  {
    name: "CSS3",
    category: "frontend",
    brandColor: "#1572B6",
    icon: FaCss3Alt,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Portfolio Frontend", href: "/projects" }],
  },
  {
    name: "Bootstrap",
    category: "frontend",
    brandColor: "#7952B3",
    icon: FaBootstrap,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "TournyMate", href: "/projects" }],
  },
  {
    name: "SQL",
    category: "backend",
    brandColor: "#00758F",
    icon: SiMysql,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Project Data Layer", href: "/projects" }],
  },
  {
    name: "JavaFX",
    category: "frontend",
    brandColor: "#EA2D2E",
    icon: SiOpenjdk,
    tier: "Working",
    lastUsed: "March 2026",
    projects: [{ label: "Desktop UI Client", href: "/projects" }],
  },
  {
    name: "Arduino",
    category: "iot",
    brandColor: "#00979D",
    icon: SiArduino,
    tier: "Working",
    lastUsed: "February 2026",
    projects: [{ label: "Automated Fish Pond Monitoring", href: "/projects" }],
  },
  {
    name: "Git",
    category: "tools",
    brandColor: "#F05032",
    icon: FaGitAlt,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "All Projects", href: "/projects" }],
  },
  {
    name: "GitHub",
    category: "tools",
    brandColor: "#F8FAFC",
    textColor: "#0B1220",
    icon: FaGithub,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "All Projects", href: "/projects" }],
  },
  {
    name: "IntelliJ IDEA",
    category: "tools",
    brandColor: "#000000",
    textColor: "#F8FAFC",
    icon: SiIntellijidea,
    tier: "Core",
    lastUsed: "June 2026",
    projects: [{ label: "Desktop Management Tool", href: "/projects" }],
  },
  {
    name: "Codeforces",
    category: "tools",
    brandColor: "#1F8ACB",
    icon: SiCodeforces,
    tier: "Working",
    lastUsed: "June 2026",
    projects: [{ label: "DSA Problem Sets", href: "/projects" }],
  },
]
